// 生成物：node tools/gen-read-aloud-packs.mjs（源 = ../20260903 PWA Models 的 voices/*.json + 它们点名的 packs/*/manifest.json）。勿手改。
// packId = sha256(manifest.json 原字节) = app 钉死的信任根；分片字节从任何主机 / 文件来都先对 manifest.chunks[].sha256 再用。
// generated by tools/gen-read-aloud-packs.mjs (Claude Fable 5.1)
import type { EmbeddedPack, VoiceDef } from "@internal/read-aloud";
export const READ_ALOUD_VOICES: Record<string, VoiceDef> = {

};
export const READ_ALOUD_PACKS: Record<string, EmbeddedPack> = {

};
